### ISSUE TITLE
HDR to SDR

### ISSUE THREAD

**Issue by winoni71** [quietvoid/subtitle_tonemap#1]
Hi, I was wondering if there's any way to use this application for doing the exact opposite of what it does, I would like to be able to tone map HDR subtitles to SDR.

Thank you.

**Comment by quietvoid** [comment]
You can probably use `--fixed` and `--percentage 90`, that would give you more white subtitles.

**Comment by winoni71** [comment]
> 
> 
> You can probably use `--fixed` and `--percentage 90`, that would give you more white subtitles.

Thank you, it worked perfectly!
