### ISSUE TITLE
#help_wanted

### ISSUE THREAD

**Issue by niwmut** [quietvoid/subtitle_tonemap#3]
Thanks for this repo. Is there any options available to check how much % i need to make tone mapped? Like for HDR sometimes it is 55, 56,60 or other numbers and SDR 90,95 etc.

**Comment by quietvoid** [comment]
No, but you can always use `--fixed` with `--color` instead.

**Comment by niwmut** [comment]
Sorry i know the color. For HDR it's kinda grey and for sdr it's white. I wanted to know how to check the % to make the subtitle white to grey? Sometimes it's 55, 60 etc

**Comment by quietvoid** [comment]
> Sorry i know the color. For HDR it's kinda grey and for sdr it's white. I wanted to know how to check the % to make the subtitle white to grey? Sometimes it's 55, 60 etc

Like I said:
> The alternative is extracting the images yourself, and using an image editor's color pipette to find out what the original colour is.

**Comment by niwmut** [comment]
> If it's white, it'll tell you a value out of 255. You can do the math to get the %. Otherwise, reread the comment I posted before.

Thanks for the solution
